// AUTO-GENERATED reference data for AppIcon.vue -- fa- name -> Lucide component.
// Regenerate by re-running the icon migration script if new dynamic icon names are added.
import {
  ArrowLeft,
  ArrowRight,
  ArrowRightLeft,
  Award,
  Ban,
  Banknote,
  Bell,
  Bot,
  Briefcase,
  CalendarDays,
  CalendarX,
  Camera,
  ChartColumn,
  ChartLine,
  ChartPie,
  Check,
  CheckCheck,
  CircleAlert,
  CircleCheck,
  CirclePause,
  CircleQuestionMark,
  CircleX,
  ClipboardCheck,
  ClipboardList,
  Clock,
  ClockAlert,
  Cloud,
  CloudFog,
  CloudLightning,
  CloudRain,
  CloudSun,
  Coins,
  CreditCard,
  Ellipsis,
  Factory,
  File,
  FileCheck,
  FileImage,
  FilePenLine,
  FilePlus,
  FileText,
  Fuel,
  Gauge,
  Globe,
  HandCoins,
  Handshake,
  HardHat,
  Headset,
  HeartHandshake,
  HeartPulse,
  Hourglass,
  House,
  HouseHeart,
  IdCard,
  Image,
  Inbox,
  Key,
  Landmark,
  Layers,
  Lightbulb,
  ListChecks,
  LoaderCircle,
  Lock,
  Mail,
  MailOpen,
  MapPin,
  MapPinned,
  MessageCircleMore,
  MessageSquareHeart,
  MessageSquareWarning,
  MessagesSquare,
  Megaphone,
  Newspaper,
  PartyPopper,
  Pause,
  Pencil,
  Phone,
  Play,
  PlugZap,
  PowerOff,
  Receipt,
  RotateCcwClock,
  Route,
  Settings,
  ShieldCheck,
  ShieldUser,
  SlidersHorizontal,
  Smartphone,
  Sparkles,
  Star,
  Sun,
  Tags,
  ThumbsDown,
  ThumbsUp,
  Trash2,
  TrendingUp,
  TriangleAlert,
  User,
  UserCheck,
  UserCog,
  UserLock,
  UserPlus,
  UserRound,
  Users,
  UsersRound,
  Wallet,
  Wrench,
  X,
  Zap,
} from "@lucide/vue";

export const DYNAMIC_ICON_MAP = {
  "fa-arrow-trend-up": TrendingUp,
  "fa-ban": Ban,
  "fa-arrow-left": ArrowLeft,
  "fa-arrow-right": ArrowRight,
  "fa-bell": Bell,
  "fa-bolt": Zap,
  "fa-briefcase": Briefcase,
  "fa-building-columns": Landmark,
  "fa-bullhorn": Megaphone,
  "fa-calendar-day": CalendarDays,
  "fa-calendar-days": CalendarDays,
  "fa-calendar-xmark": CalendarX,
  "fa-camera": Camera,
  "fa-certificate": Award,
  "fa-champagne-glasses": PartyPopper,
  "fa-chart-line": ChartLine,
  "fa-chart-pie": ChartPie,
  "fa-chart-simple": ChartColumn,
  "fa-check": Check,
  "fa-check-double": CheckCheck,
  "fa-circle-check": CircleCheck,
  "fa-circle-exclamation": CircleAlert,
  "fa-circle-pause": CirclePause,
  "fa-circle-question": CircleQuestionMark,
  "fa-circle-xmark": CircleX,
  "fa-clipboard-check": ClipboardCheck,
  "fa-clipboard-list": ClipboardList,
  "fa-clock": Clock,
  "fa-clock-rotate-left": RotateCcwClock,
  "fa-cloud": Cloud,
  "fa-cloud-bolt": CloudLightning,
  "fa-cloud-rain": CloudRain,
  "fa-cloud-showers-heavy": CloudRain,
  "fa-cloud-sun": CloudSun,
  "fa-coins": Coins,
  "fa-comment-dots": MessageCircleMore,
  "fa-comment-exclamation": MessageSquareWarning,
  "fa-comment-medical": MessageSquareHeart,
  "fa-comments": MessagesSquare,
  "fa-credit-card": CreditCard,
  "fa-ellipsis": Ellipsis,
  "fa-envelope": Mail,
  "fa-envelope-open-text": MailOpen,
  "fa-file": File,
  "fa-file-circle-check": FileCheck,
  "fa-file-circle-plus": FilePlus,
  "fa-file-contract": FilePenLine,
  "fa-file-image": FileImage,
  "fa-file-invoice": Receipt,
  "fa-file-invoice-dollar": Receipt,
  "fa-file-lines": FileText,
  "fa-file-pdf": FileText,
  "fa-file-signature": FilePenLine,
  "fa-gas-pump": Fuel,
  "fa-gauge": Gauge,
  "fa-gauge-high": Gauge,
  "fa-gear": Settings,
  "fa-gears": Settings,
  "fa-globe": Globe,
  "fa-hand-holding-hand": Handshake,
  "fa-handshake": Handshake,
  "fa-hands-holding-child": HeartHandshake,
  "fa-headset": Headset,
  "fa-heart-pulse": HeartPulse,
  "fa-hourglass-end": Hourglass,
  "fa-hourglass-half": Hourglass,
  "fa-house": House,
  "fa-house-chimney-medical": HouseHeart,
  "fa-house-user": House,
  "fa-id-card": IdCard,
  "fa-image": Image,
  "fa-inbox": Inbox,
  "fa-industry": Factory,
  "fa-key": Key,
  "fa-layer-group": Layers,
  "fa-lightbulb": Lightbulb,
  "fa-list-check": ListChecks,
  "fa-location-dot": MapPin,
  "fa-lock": Lock,
  "fa-map-location-dot": MapPinned,
  "fa-mobile-screen-button": Smartphone,
  "fa-money-bill-wave": Banknote,
  "fa-newspaper": Newspaper,
  "fa-pause": Pause,
  "fa-pause-circle": CirclePause,
  "fa-pen": Pencil,
  "fa-people-group": UsersRound,
  "fa-people-roof": HouseHeart,
  "fa-phone": Phone,
  "fa-play": Play,
  "fa-plug-circle-bolt": PlugZap,
  "fa-power-off": PowerOff,
  "fa-receipt": Receipt,
  "fa-right-left": ArrowRightLeft,
  "fa-robot": Bot,
  "fa-route": Route,
  "fa-sack-dollar": HandCoins,
  "fa-screwdriver-wrench": Wrench,
  "fa-shield-halved": ShieldCheck,
  "fa-sliders": SlidersHorizontal,
  "fa-smog": CloudFog,
  "fa-sparkles": Sparkles,
  "fa-spinner": LoaderCircle,
  "fa-star": Star,
  "fa-sun": Sun,
  "fa-tags": Tags,
  "fa-thumbs-down": ThumbsDown,
  "fa-thumbs-up": ThumbsUp,
  "fa-trash": Trash2,
  "fa-triangle-exclamation": TriangleAlert,
  "fa-user": User,
  "fa-user-check": UserCheck,
  "fa-user-clock": ClockAlert,
  "fa-user-gear": UserCog,
  "fa-user-group": UsersRound,
  "fa-user-helmet-safety": HardHat,
  "fa-user-lock": UserLock,
  "fa-user-plus": UserPlus,
  "fa-users": Users,
  "fa-user-shield": ShieldUser,
  "fa-user-tie": UserRound,
  "fa-wallet": Wallet,
  "fa-xmark": X,
};
