export default [
  // ==================== أدمن ====================
  {
    label: "لوحة التحكم",
    labelKey: "menu.dashboard",
    icon: "fa-solid fa-house",
    route: "admin.dashboard",
    roles: ["admin"],
    group: "عام",
    groupKey: "menu_groups.general",
  },
  {
    label: "المولدات",
    labelKey: "menu.generators",
    icon: "fa-solid fa-plug-circle-bolt",
    route: "admin.generators",
    roles: ["admin"],
    permission: "generators.view",
    group: "العمليات",
    groupKey: "menu_groups.operations",
    badgeKey: "generators_pending_verification",
  },
  {
    label: "أصحاب المولدات و طلبات الانضمام",
    labelKey: "menu.generator_owners",
    icon: "fa-solid fa-user-tie",
    route: "admin.generator-owners",
    roles: ["admin"],
    permission: "generators.view",
    group: "العمليات",
    groupKey: "menu_groups.operations",
  },
  {
    label: "المشتركون و الاشتراكات",
    labelKey: "menu.subscribers",
    icon: "fa-solid fa-user-group",
    route: "admin.subscribers",
    roles: ["admin"],
    permission: "subscriptions.view",
    group: "العمليات",
    groupKey: "menu_groups.operations",
  },
  {
    label: "قراءات العدادات",
    labelKey: "menu.meter_readings",
    icon: "fa-solid fa-gauge",
    route: "admin.meter-readings",
    roles: ["admin"],
    permission: "meter-readings.view",
    group: "العمليات",
    groupKey: "menu_groups.operations",
  },
  {
    label: "الفواتير",
    labelKey: "menu.invoices",
    icon: "fa-solid fa-file-invoice",
    route: "admin.invoices",
    roles: ["admin"],
    permission: "invoices.view",
    group: "المالية",
    groupKey: "menu_groups.finance",
    badgeKey: "invoices_overdue",
  },
  {
    label: "الدفعات و طرق الدفع",
    labelKey: "menu.payments",
    icon: "fa-solid fa-wallet",
    route: "admin.payments",
    roles: ["admin"],
    permission: "payments.view",
    group: "المالية",
    groupKey: "menu_groups.finance",
    badgeKey: "payments_pending",
  },
  {
    label: "العروض",
    labelKey: "menu.offers",
    icon: "fa-solid fa-tags",
    route: "admin.offers",
    roles: ["admin"],
    permission: "offers.view",
    group: "المالية",
    groupKey: "menu_groups.finance",
  },
  {
    label:  "الفنيون و الصيانة",
    labelKey: "menu.technicians",
    icon: "fa-solid fa-screwdriver-wrench",
    route: "admin.technicians",
    roles: ["admin"],
    permission: "technicians.view",
    group: "الصيانة والدعم",
    groupKey: "menu_groups.maintenance_support",
  },
  {
    label: "الشكاوى",
    labelKey: "menu.complaints",
    icon: "fa-solid fa-comment-dots",
    route: "admin.complaints",
    roles: ["admin"],
    permission: "complaints.view",
    group: "الصيانة والدعم",
    groupKey: "menu_groups.maintenance_support",
    badgeKey: "complaints_open",
  },
  {
    label: "الأعطال",
    labelKey: "menu.faults",
    icon: "fa-solid fa-triangle-exclamation",
    route: "admin.faults",
    roles: ["admin"],
    permission: "faults.view",
    group: "الصيانة والدعم",
    groupKey: "menu_groups.maintenance_support",
    badgeKey: "faults_pending",
  },
    {
    label: "ملخص الأحياء",
    labelKey: "neighborhood_dashboard_page.title",
    icon: "fa-solid fa-map-location-dot",
    route: "admin.neighborhoods",
    roles: ["admin"],
    permission: "neighborhoods.dashboard",
    group: "العمليات",
    groupKey: "menu_groups.operations",
  },
  {
    label: "المستخدمون و والصلاحيات",
    labelKey: "menu.users",
    icon: "fa-solid fa-users",
    route: "admin.users",
    roles: ["admin"],
    permission: "users.view",
    group: "النظام",
    groupKey: "menu_groups.system",
    badgeKey: "users_locked",
  },
  {
    label: "التقارير",
    labelKey: "menu.reports",
    icon: "fa-solid fa-chart-line",
    route: "admin.reports",
    roles: ["admin"],
    permission: "platform-commissions.view",
    group: "النظام",
    groupKey: "menu_groups.system",
  },
  {
    label: "سجل تسجيل الدخول",
    labelKey: "menu.login_logs",
    icon: "fa-solid fa-shield-halved",
    route: "admin.login-logs",
    roles: ["admin"],
    group: "النظام",
    groupKey: "menu_groups.system",
  },
  {
    label: "المقالات",
    labelKey: "menu.articles",
    icon: "fa-solid fa-newspaper",
    route: "admin.articles",
    roles: ["admin"],
    group: "النظام",
    groupKey: "menu_groups.system",
  },
  {
    label: "إعدادات المنصة",
    labelKey: "menu.settings",
    icon: "fa-solid fa-gear",
    route: "admin.settings",
    roles: ["admin"],
    group: "النظام",
    groupKey: "menu_groups.system",
  },
  {
    label: "المحادثات",
    labelKey: "menu.messages",
    icon: "fa-solid fa-comment-dots",
    route: "admin.messages",
    roles: ["admin"],
    permission: "conversations.view",
    group: "التواصل",
    groupKey: "menu_groups.communication",
    badgeKey: "messages_unread",
  },
  {
    label: "رسائل التواصل",
    labelKey: "menu.contact_messages",
    icon: "fa-solid fa-envelope-open-text",
    route: "admin.contact-messages",
    roles: ["admin"],
    group: "التواصل",
    groupKey: "menu_groups.communication",
    badgeKey: "contact_messages_new",
  },
  {
    label: "إعدادات حسابي",
    labelKey: "menu.account_settings",
    icon: "fa-solid fa-user-gear",
    route: "admin.account-settings",
    roles: ["admin"],
    group: "الحساب",
    groupKey: "menu_groups.account",
  },

  // ==================== صاحب المولد ====================
  {
    label: "لوحة التحكم",
    labelKey: "menu.dashboard",
    icon: "fa-solid fa-house",
    route: "owner.dashboard",
    roles: ["generator_owner"],
    group: "عام",
    groupKey: "menu_groups.general",
  },
  {
    label: "المولدات",
    labelKey: "menu.generators",
    icon: "fa-solid fa-bolt",
    route: "owner.generators",
    roles: ["generator_owner"],
    permission: "generators.view",
    group: "العمليات",
    groupKey: "menu_groups.operations",
  },
  {
    label: "المشتركون و الاشتراكات",
    labelKey: "menu.subscribers",
    icon: "fa-solid fa-user-group",
    route: "owner.subscribers",
    roles: ["generator_owner"],
    permission: "subscriptions.view",
    group: "العمليات",
    groupKey: "menu_groups.operations",
  },
  {
    label: "قراءات العداد",
    labelKey: "menu.meter_readings",
    icon: "fa-solid fa-gauge",
    route: "owner.meter-readings",
    roles: ["generator_owner"],
    permission: "meter-readings.view",
    group: "العمليات",
    groupKey: "menu_groups.operations",
  },
  {
    label: "الفواتير",
    labelKey: "menu.invoices",
    icon: "fa-solid fa-file-invoice",
    route: "owner.invoices",
    roles: ["generator_owner"],
    permission: "invoices.view",
    group: "المالية",
    groupKey: "menu_groups.finance",
  },
  {
    label: "العروض",
    labelKey: "menu.offers",
    icon: "fa-solid fa-tags",
    route: "owner.offers",
    roles: ["generator_owner"],
    permission: "offers.view",
    group: "المالية",
    groupKey: "menu_groups.finance",
  },
  {
    label: "الفنيون",
    labelKey: "menu.technicians",
    icon: "fa-solid fa-screwdriver-wrench",
    route: "owner.technicians",
    roles: ["generator_owner"],
    permission: "technicians.view",
    group: "الصيانة والدعم",
    groupKey: "menu_groups.maintenance_support",
  },
  {
    label: "الأعطال",
    labelKey: "menu.faults",
    icon: "fa-solid fa-bolt",
    route: "owner.faults",
    roles: ["generator_owner"],
    permission: "faults.view",
    group: "الصيانة والدعم",
    groupKey: "menu_groups.maintenance_support",
    /* لا badgeKey هنا عمدًا: عدّاد faults_pending بـ SidebarBadgeService
     * غير مُصفّى (Fault::count عام بلا owner_id) ومسار admin/sidebar/badge-counts
     * محصور بـ role:admin — لو أُضيف هنا فسيفشل الطلب بصمت لصاحب المولد (403)
     * كل 60 ثانية، وقد يُسقط تحديث badge الرسائل غير المقروءة معه ضمن
     * نفس Promise.all بستور sidebarBadges. */
  },
  {
    label: "الشكاوى",
    labelKey: "menu.complaints",
    icon: "fa-solid fa-triangle-exclamation",
    route: "owner.complaints",
    roles: ["generator_owner"],
    permission: "complaints.view",
    group: "الصيانة والدعم",
    groupKey: "menu_groups.maintenance_support",
  },
  {
    label: "طلبات الخدمة",
    labelKey: "menu.service_requests",
    icon: "fa-solid fa-bolt-lightning",
    route: "owner.service-requests",
    roles: ["generator_owner"],
    permission: "service-requests.view",
    group: "الصيانة والدعم",
    groupKey: "menu_groups.maintenance_support",
  },
  {
    label: "التقارير",
    labelKey: "menu.reports",
    icon: "fa-solid fa-chart-line",
    route: "owner.reports",
    roles: ["generator_owner"],
    permission: "platform-commissions.view",
    group: "المالية",
    groupKey: "menu_groups.finance",
  },
  {
    label: "المحادثات",
    labelKey: "menu.messages",
    icon: "fa-solid fa-comment-dots",
    route: "owner.messages",
    roles: ["generator_owner"],
    permission: "conversations.view",
    group: "التواصل",
    groupKey: "menu_groups.communication",
  },
  {
    label: "إعدادات حسابي",
    labelKey: "menu.account_settings",
    icon: "fa-solid fa-user-gear",
    route: "owner.settings",
    roles: ["generator_owner"],
    group: "الحساب",
    groupKey: "menu_groups.account",
  },

  // ==================== الفني ====================
  {
    label: "لوحة التحكم",
    labelKey: "menu.dashboard",
    icon: "fa-solid fa-house",
    route: "technician.dashboard",
    roles: ["technician"],
    group: "عام",
    groupKey: "menu_groups.general",
  },
  {
    label: "مهامي وقراءاتي",
    labelKey: "menu.my_tasks",
    icon: "fa-solid fa-list-check",
    route: "technician.dashboard",
    roles: ["technician"],
    permission: "technician-tasks.view",
    group: "العمليات",
    groupKey: "menu_groups.operations",
  },
  {
    label: "المحادثات",
    labelKey: "menu.messages",
    icon: "fa-solid fa-comment-dots",
    route: "technician.messages",
    roles: ["technician"],
    permission: "conversations.view",
    group: "التواصل",
    groupKey: "menu_groups.communication",
  },
  {
    label: "إعدادات حسابي",
    labelKey: "menu.account_settings",
    icon: "fa-solid fa-user-gear",
    route: "technician.settings",
    roles: ["technician"],
    group: "الحساب",
    groupKey: "menu_groups.account",
  },
  // ==================== المشترك ====================
  {
    label: "لوحة التحكم",
    labelKey: "menu.dashboard",
    icon: "fa-solid fa-house",
    route: "subscriber.dashboard",
    roles: ["subscriber"],
    group: "عام",
    groupKey: "menu_groups.general",
  },
  {
    label:  "اشتراكي  و تصفح المولدات ",
    labelKey: "menu.my_subscription",
    icon: "fa-solid fa-file-circle-check",
    route: "subscriber.subscription",
    roles: ["subscriber"],
    group: "العمليات",
    groupKey: "menu_groups.operations",
  },
  {
    label: "قراءات العداد",
    labelKey: "menu.meter_readings",
    icon: "fa-solid fa-gauge",
    route: "subscriber.meter-readings",
    roles: ["subscriber"],
    group: "العمليات",
    groupKey: "menu_groups.operations",
  },
  {
    label: "فواتيري و دفعاتي ",
    labelKey: "menu.my_invoices",
    icon: "fa-solid fa-file-invoice",
    route: "subscriber.invoices",
    roles: ["subscriber"],
    group: "المالية",
    groupKey: "menu_groups.finance",
  },
  {
    label: "العروض",
    labelKey: "menu.offers",
    icon: "fa-solid fa-tags",
    route: "subscriber.offers",
    roles: ["subscriber"],
    permission: "offers.view",
    group: "المالية",
    groupKey: "menu_groups.finance",
  },
  {
    label: "مركز الدعم",
    labelKey: "menu.support_center",
    icon: "fa-solid fa-headset",
    route: "subscriber.support",
    roles: ["subscriber"],
    group: "الصيانة والدعم",
    groupKey: "menu_groups.maintenance_support",
  },
  {
    label: "المحادثات",
    labelKey: "menu.messages",
    icon: "fa-solid fa-comment-dots",
    route: "subscriber.messages",
    roles: ["subscriber"],
    permission: "conversations.view",
    group: "التواصل",
    groupKey: "menu_groups.communication",
  },
  {
    label: "الإشعارات",
    labelKey: "common.notifications",
    icon: "fa-solid fa-bell",
    route: "subscriber.notifications",
    roles: ["subscriber"],
    group: "التواصل",
    groupKey: "menu_groups.communication",
  },
  {
    label: "إعدادات حسابي",
    labelKey: "menu.account_settings",
    icon: "fa-solid fa-user-gear",
    route: "subscriber.settings",
    roles: ["subscriber"],
    group: "الحساب",
    groupKey: "menu_groups.account",
  },
];